export const GET_CONTACTS_LIST_SUCCEED = "GET_CONTACTS_LIST_SUCCEED";

export const HANDLE_CREATE_CONTACT_SUCCEED = "HANDLE_CREATE_CONTACT_SUCCEED";

export const HANDLE_INPUT_CHANGE = "HANDLE_INPUT_CHANGE";

export const HANDLE_OPEN_DELETED = "HANDLE_OPEN_DELETED";

export const HANDLE_CLOSE_DELETED = "HANDLE_CLOSE_DELETED";

export const HANDLE_OPEN_EDIT = "HANDLE_OPEN_EDIT";

export const HANDLE_CLOSE_EDIT = "HANDLE_CLOSE_EDIT";