export const GET_DEBTS_OWNER_LIST_SUCCEED = "GET_DEBTS_OWNER_LIST_SUCCEED";

export const GET_DEBTS_OTHER_LIST_SUCCEED = "GET_DEBTS_OTHER_LIST_SUCCEED";

export const HANDLE_CREATE_DEBT_SUCCEED = "HANDLE_CREATE_DEBT_SUCCEED";

export const HANDLE_INPUT_CHANGE = "HANDLE_INPUT_CHANGE";

export const GET_ALL_ACCOUNT = "GET_ALL_ACCOUNT";
