export const GET_STAFFS_LIST_SUCCEED = "GET_STAFFS_LIST_SUCCEED";

export const OPEN_DELETE_DIALOG_CONFIRM =
"OPEN_DELETE_DIALOG_CONFIRM";

export const CLOSE_DELETE_DIALOG_CONFIRM =
"CLOSE_DELETE_DIALOG_CONFIRM";

export const HANDLE_DELETE_DIALOG_CONFIRM_SUCCEED = "HANDLE_DELETE_DIALOG_CONFIRM_SUCCEED";

export const HANDLE_DELETE_DIALOG_CONFIRM_ERROR = "HANDLE_DELETE_DIALOG_CONFIRM_ERROR";

export const OPEN_EDIT_DIALOG_CONFIRM =
"OPEN_EDIT_DIALOG_CONFIRM";

export const CLOSE_EDIT_DIALOG_CONFIRM =
"CLOSE_EDIT_DIALOG_CONFIRM";

export const HANDLE_EDIT_DIALOG_CONFIRM_SUCCEED = "HANDLE_EDIT_DIALOG_CONFIRM_SUCCEED";

export const HANDLE_EDIT_DIALOG_CONFIRM_ERROR = "HANDLE_EDIT_DIALOG_CONFIRM_ERROR";

export const HANDLE_INPUT_CHANGE="HANDLE_INPUT_CHANGE";

